### ISSUE TITLE
CARTA PRESENTACION

### ISSUE THREAD

**Issue by VeroGaM** [Latorg/Tecno_SLP#4]
SE SUBIO AL GOOGLE DRIVE EL ARCHIVO "CARTA PRESENTACION TEPSA.DOC"

ESTA EN PROPUESTA, SE LE ENVIO A BETTY Y MONREAL POR CORREO, PREGUNTARLE A BETTY PORQUE AL PARECER QUIEREN PONER Y QUITAR LOGOS DE MARCAS DE LA IMAGEN QUE YA VIENE INCLUIDA EN EL ARCHIVO, HAY QUE MODIFICAR APARTE PORQUE ESTAN EN UNA SOLA IMAGEN

UNA VEZ MODIFICADA ENVIAR AL ARCHIVO EN WORD Y PDF POR CORREO A BETTY, MONREAL, MARICELA Y ANA MESTAS

**Comment by VeroGaM** [comment]
SE SUBIO EN LA CARPETA "FORMATOS TEPSA PAPELERIA"

**Comment by Latorg** [comment]
El Sr Mestas envia un correo al Inge con la correccion de la carta

**Comment by Latorg** [comment]
Se sube al dirve el documento y se envian a los correos de Monreal, Maricela, Ana Mestas, Vero Galicia, Betty con el texto corregido por sr mestas y los logos actualizados

Logos que se quitan: Legrand, Bticino, Tecno Lite, Panduit, Belden
Logos que se agregan: Supra, Jupiter, Deplayusa, Eaton, Hubbell
